mutation {
    deleteUser(id: "") {
    _id
    }
}
# create a photo in playground
mutation {
    createPhoto(
        data: {
            author: { connect: "312744115794084416" }
            src: "https://picsum.photos/200"
            posted: "2011-10-05T14:48:00.000Z"
    }
    ) {
        author {
        email
    }
    }
}
# get all photos from user oldest to newest
query {
findUserByID(id: "312756914412847682") {
    photos {
      data {
        _id
      }
    }
  }
}

# get all photos by user with ID in reverse OLD (ID)
query {
  getProfilePhotos(id: "312756914412847682") {
    data {
      _id
    }
  }
}

# get all photos by user with ID in reverse NEW (username)

query {
  getProfilePhotos(username: "keithers98") {
    data {
      src
    }
  }
}


# get profile info 
query {
  findUserByID(id: "312904030864015938") {
    headline
    fullName
    followingCount
    followerCount
    bio
  }
}

#get user by username 
query {
  getUserByUsername(username: "keithers98") {
    _id
  }
}

# get timeline 

query {
  getTimeline(_size: 10) {
    data {
      src
      likeCount
      comments
      caption
    }
  }
}

# delete photo by photo ID
mutation {
  deletePhoto(id: "312951668549354050") {
    src
  }
}