mutation {
    deleteUser(id: "") {
    _id
    }
}
# create a photo in playground
mutation {
    createPhoto(
        data: {
            author: { connect: "312744115794084416" }
            src: "https://picsum.photos/200"
            posted: "2011-10-05T14:48:00.000Z"
    }
    ) {
        author {
        email
    }
    }
}
# get all photos from user oldest to newest
query {
findUserByID(id: "312756914412847682") {
    photos {
      data {
        _id
      }
    }
  }
}

# get all photos by user with ID in reverse
query {
  getProfilePhotos(id: "312756914412847682") {
    data {
      _id
    }
  }
}

# get profile info 
query {
  findUserByID(id: "312904030864015938") {
    headline
    fullName
    followingCount
    followerCount
    bio
  }
}
