mutation {
  deleteUser(id: "") {
    _id
  }
}


mutation {
  createPhoto(
    data: {
      author:{ connect:  "312744115794084416" }
      src: "https://picsum.photos/200"
      posted: "2011-10-05T14:48:00.000Z"
    }
  ){
    author{email}
  }
}
