type User {
  email: String! @unique
  username: String @unique
  fullName: String
  dateCreated: Time!
  following: [Follow] @relation(name: "following")
}

type Follow {
  user: User
  follows: User @relation(name: "following")
}

type Mutation {
  loginUser(input: LoginUserInput!): LoginUserPayload! @resolver(name: "login_user")
}

input LoginUserInput {
  email: String!
}
type LoginUserPayload @embedded {
  token: String!
  exp: Time!
  userInfo: User!
}

# TODO: Add base types from adaptation
