mutation {
  deleteUser(id: "") {
    _id
  }
}
# create a photo in playground
mutation {
  createPhoto(
    data: {
      author: { connect: "312744115794084416" }
      src: "https://picsum.photos/200"
      posted: "2011-10-05T14:48:00.000Z"
      caption: "anything"
    }
  ) {
    _id
  }
}
# get all photos from user oldest to newest
query {
  findUserByID(id: "312756914412847682") {
    photos {
      data {
        _id
      }
    }
  }
}

# get all photos by user with ID in reverse OLD (ID)
query {
  getProfilePhotos(id: "312756914412847682") {
    data {
      _id
    }
  }
}

# get all photos by user with ID in reverse NEW (username)

query {
  getProfilePhotos(username: "keithers98") {
    data {
      src
      likeCount
      caption
    }
  }
}

# get profile info by usernmae
query {
  getUserByUsername(username: "fang") {
    headline
    fullName
    followingCount
    followerCount
    bio
    username
    profileImgSrc
    _id
    followers {
      data {
        user {
          username
          _id
        }
        _id
      }
    }
  }
}


# get timeline

query {
  getTimeline(_size: 10) {
    data {
      author {
        username
      }
      src
      likeCount
      comments {
        data {
          author {
            username
          }
          text
        }
      }
      caption
    }
  }
}

# delete photo by photo ID
mutation {
  deletePhoto(id: "312951668549354050") {
    src
  }
}

#create follow
mutation {
  createFollow(data: { user: { connect: "312950643766592066" }, follows: { connect: "312836571385561665" } }) {
    _id
  }
}

#delete follow 
mutation {
  deleteFollow(id: "313291905631781442") {
    user {
      username
    }
    follows {
      username
    }
  }
}

#get explore 
query {
  getExplore(_size: 10) {
    data {
      author {
        username
      }
      src
      caption
      likeCount
      liked {
        data {
          username
        }
      }
    }
  }
}

#create a comment 
mutation {
  createComment(
    data: {
      author: { connect: "312950643766592066" }
      photo: { connect: "312955337078473280" }
      text: "Wow this is great!"
      posted: "2021-10-25T00:57:44Z"
    }
  ) {
    _id
  }
}