type User {
  email: String! @unique
  username: String @unique
  fullName: String
  created: Time!
  onboard: Boolean!
  following: [Follow] @relation(name: "following")
  followers: [Follow] @relation(name: "followers")
  followerCount: Int
  followingCount: Int
  likes: [Photo] @relation
  bio: String
  headline: String
  photos: [Photo] @relation(name: "user_photos")
  profileImgSrc: String
  avatar: Media
}

type Follow {
  user: User! @relation(name: "following")
  follows: User! @relation(name: "followers")
}

type Photo {
  author: User! @relation(name: "user_photos")
  media: Media!
  posted: Time!
  caption: String
  liked: [User] @relation
  comments: [Comment] @relation
  likeCount: Int
}

type Media @embedded {
  src: String!
  """
  imagekit fileID
  """
  id: ID!
  width: Int!
  height: Int!
}

type Comment {
  author: User!
  photo: Photo!
  text: String!
  posted: Time!
}

type Query {
  """
  `username`: Defaults to timeline. empty str = explore, otherwise accesses profile photos.
  """
  getTimeline(username: String): [Photo]! @resolver(name: "get_timeline", paginated: true)
  getUserByUsername(username: String!): User! @resolver(name: "get_user_by_username")
  searchUser(username: String!): [User]! @resolver(name: "search_user", paginated: true)
  getPostByID(id: ID!): PostPayload! @resolver(name: "get_post_by_id")
}

type Mutation {
  loginUser(input: LoginUserInput!): LoginUserPayload! @resolver(name: "login_user")
  logoutUser(input: LogoutUserInput!): Boolean! @resolver(name: "logout_user")
  likePhoto(input: LikePhotoInput!): Photo! @resolver(name: "like_photo")
  followUser(input: FollowUserInput!): User! @resolver(name: "follow_user")
}

input LoginUserInput {
  email: String!
}
type LoginUserPayload @embedded {
  token: String!
  exp: Time!
  userInfo: User!
}
input LogoutUserInput {
  allDevices: Boolean!
}

input LikePhotoInput {
  photoID: ID!
  value: Boolean!
}
input FollowUserInput {
  userID: ID!
  value: Boolean!
}

input GetPhotoInput {
  photoID: ID!
}

type PostPayload @embedded {
  author: User!
  photo: Photo!
  """
  dynamic, only available through manually defined queries/mutations
  """
  followedByUser: Boolean!
  likedByUser: Boolean!
  # starredByUser: Boolean
}

# TODO: Check base types from adaptation have all been added to schema
# * VSCode >Fauna: Upload GraphQL Schema
